### ISSUE TITLE
Create separate endpoints

### ISSUE THREAD

**Issue by PeterSulcs** [changer666666/capstone_backend_restful#3]
Would recommend using flask decorators to create dedicated GET endpoints for the major functions of the web service.

Something along the lines of:
```
{BASE_URL}/datasets
{BASE_URL}/testruns?dataset={dataset}
{BASE_URL}/parameters?dataset={dataset}
{BASE_URL}/plots?dataset={dataset}&testrun={testrun}
```

I am familiar with the `@app.route` syntax, but there are many ways of doing it, including an Object Oriented method using Flask-restless (which I think might be the approach you have taken).

https://flask.palletsprojects.com/en/1.1.x/quickstart/#routing

**Comment by changer666666** [comment]
> Would recommend using flask decorators to create dedicated GET endpoints for the major functions of the web service.
> 
> Something along the lines of:
> 
> ```
> {BASE_URL}/datasets
> {BASE_URL}/testruns?dataset={dataset}
> {BASE_URL}/parameters?dataset={dataset}
> {BASE_URL}/plots?dataset={dataset}&testrun={testrun}
> ```
> 
> I am familiar with the `@app.route` syntax, but there are many ways of doing it, including an Object Oriented method using Flask-restless (which I think might be the approach you have taken).
> 
> https://flask.palletsprojects.com/en/1.1.x/quickstart/#routing

Hi Pete, I have added endpoint to URI when we want to get information of MOSFET.
I add another class "MosfetInfo" on the server. And it can receive the URI in this format '/mosfet/<int:mosfet_id>'. When the user wants to get info of MOSFET #n and he chooses the "TEST & RUN" option on the left menu and clicks "blast off", we will send the GET request from React to server. The server will return the RUL image through rest API. After we receive on the React, we can show that image on the right table part.
